controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\RegistrationForm;
use app\models\User;
use app\models\UserProfile;
use app\models\Balance;
use yii\base\Exception;
use app\models\CreateNewPasswordMasterPinForm;
use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\MasterPinResetRequestForm;
use app\models\ResetMasterPinForm;
use app\models\ResendPasswordSecurityPinResetLinkForm;
use yii\data\Pagination;
use app\models\Package;
use yii\helpers\Url;
use \app\models\CreatePasswordMasterPinForm;
use \app\models\Genealogy;
use app\models\Transaction;
use app\models\Order;
use Yii\helpers\Utils;

class SiteController extends Controller
{
//    public $layout = "site/main";
     public $layout = "frontpage/main_trading";
//     public $layout = "frontpage/main_mining";

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout','package-detail'],
                'rules' => [
                    [
                        'actions' => ['logout','package-detail'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
//        if (!Yii::$app->user->isGuest) {
//            return $this->goHome();
//        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
            return $this->redirect(['user/index']);
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
//        echo "hi"; exit;
        return $this->render('about');
    }
    
    public function actionBlog()
    {
        
        return $this->render('blog');
    }

    public function actionShop()
    {
//        echo "hello"; exit;
        // build a DB query to get all packages with status = 1 and updated_at desc order.
        $query = Package::find()
        ->where(['status' => 1])
        ->orderBy(['updated_at' => SORT_DESC]);

        // get the total number of articles (but do not fetch the article data yet)
        $count = $query->count();

        // create a pagination object with the total count
        $pagination = new Pagination(['totalCount' => $count, 'pageSize' => Yii::$app->params['pageSize']]);


        // limit the query using the pagination and retrieve the packages
        $packages = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('shop', [
             'packages' => $packages,
             'pages' => $pagination,
        ]);
    }

    public function actionPackageDetail($id) {
        $id = base64_decode($id);
//echo Yii::$app->user->identity->id; exit;
        if (empty($id)) { // item does not exist
            throw new \yii\web\HttpException(404, 'The requested Item could not be found.');
        }

        // Check user has sufficient balance OR not to purchase this package.
        $userCash = Utils::walletMoney(Yii::$app->params['wallets']['CASH_WALLET']);

        // build a DB query to get all packages with status = 1 and updated_at desc order.
        $package = Package::find()
                ->where(['id' => $id, 'status' => 1])
                ->orderBy(['updated_at' => SORT_DESC])->one();

        if (empty($package)) { // item does not exist
            throw new \yii\web\HttpException(404, 'The requested Item could not be found.');
        }

        // Check whether user already purchase the package OR not.
        $order = Order::find()
                ->where(['user_id' => Yii::$app->user->identity->id, 'package_id' => $package->id, 'status' => 1])->one();


        return $this->render('packagedetail', [
             'package' => $package,
             'booking_confirm_link' => Url::to(['site/confirm-booking', 'id' => base64_encode($id)]),
             'is_user_has_sufficient_fund' => ($userCash >= $package->price) ? TRUE : FALSE,
             'already_purchased' => empty($order->id) ? TRUE : FALSE,
        ]);
    }

    public function actionConfirmBooking($id) {
        $id = base64_decode($id);

        if (empty($id)) { // item does not exist
            throw new \yii\web\HttpException(404, 'The requested Item could not be found.');
        }

        // build a DB query to get all packages with status = 1 and updated_at desc order.
        $model = Package::find()
                ->where(['id' => $id, 'status' => 1])
                ->orderBy(['updated_at' => SORT_DESC])->one();

        if (empty($model)) { // item does not exist
            throw new \yii\web\HttpException(404, 'The requested Item could not be found.');
        }

        $userObj = Yii::$app->user->identity;

        // Transaction
        //$transactionObj = new Transaction();
        $firstInnerTransaction = Transaction::getDb()->beginTransaction();
        try {
            // $TransactionObj = Transaction::createNewTransaction(null, Yii::$app->params['wallets']['CASH_WALLET'], null, "Package Purchase", $packageObj->price, $packageObj->price, Yii::$app->params['transaction_modes']['package_purchase']);
            $transactionObj = Transaction::createNewTransaction(null, Yii::$app->params['wallets']['CASH_WALLET'], null, Yii::$app->params['transaction_modes']['package_purchase'], $model->price, $model->price, Yii::$app->params['transaction_modes']['package_purchase']);
            // $transactionObj->createNewTransaction($userObj->id, $model, $model->price, $model->price, 'Purchase');            
            $transactionObj->save();
            $firstInnerTransaction->commit();
            
            // Find out existing balance of a user - Balance.
            // Package purchase is only from cash wallet.
            $balanceObj = Balance::find()->where(['user_id' => $userObj->id, 'wallet_id' => Yii::$app->params['wallets']['CASH_WALLET']])->one();
            $secondInnerTransaction = Balance::getDb()->beginTransaction();
            try {
                $fund = $balanceObj->amount - $model->price;
                $balanceObj->updateNewBalance($fund);
                $balanceObj->save(FALSE);
                $secondInnerTransaction->commit();

                // MoneyTransfer
                $order = new Order();
                $thirdInnerTransaction = Order::getDb()->beginTransaction();
                try {
                    $order->createPackageOrder($userObj, $model, $transactionObj);
                    $order->save();
                    $thirdInnerTransaction->commit();

                    // Give direct commission to his parent/ancestor.
                    if(!empty($userObj->parent_id)) {
                        $parentObj = User::findOne($userObj->parent_id);
                    } else {
                        $parentObj = User::findOne(1);
                    }

                    // Make an entry to the UserViewedAds.
                    // UserViewedAds::createEntry($userObj, $model, $order);
                    // Do only if user is active.
                    if ($parentObj->status == 1) {
                        // Transaction entry - For direct commission.
                        $direct_commission_perc = !empty($order->package->direct_commission) ? $order->package->direct_commission : Yii::$app->params['direct_commission'];
                        $direct_commission_fund = ( $order->package->price * $direct_commission_perc ) / 100;
                        $transactionObj = new Transaction();
                        //$transactionObj->createNewEntryInTransaction(1, \Yii::$app->params['payment_gateways']['manual_payment'], $direct_commission_fund, $direct_commission_fund, "Direct Commission", 1, 1, "Direct Commission", "Direct Commission", 3, 3, 1, $parentObj->id);
                        $transactionObj->createNewTransaction($userObj->id, Yii::$app->params['wallets']['REFERRAL_WALLET'], Yii::$app->params['wallets']['REFERRAL_WALLET'], Yii::$app->params['transaction_modes']['direct_commission'], $direct_commission_fund, $direct_commission_fund, Yii::$app->params['transaction_modes']['direct_commission'], $from_user_id = Null);

views/site/contact_mining.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/reset_password.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password container">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
            
                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password_repeat')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Reset', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/shop_1.php
<?php

use borales\extensions\phoneInput\PhoneInput;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\jui\AutoComplete;
use yii\helpers\Url;
use yii\helpers\Utils;
use yii\widgets\LinkPager;

$this->title = 'Packages';
$this->params['breadcrumbs'][] = $this->title;
?>

<style>
/*    .page-title1.little-pad {
    background: url(/images/blog.jpg);
}*/
.bgimg{
background: url(/images/blog.jpg);
}
.sociallink{
   background-color: #fed602;
}

    </style>
<section class=" bgimg section lb page-title1 little-pad">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-big-title clearfix text-center">
                	                    <div class="title-banner-bred">
                        <div class="title-subtitle-content">
                            <h3>NurseryPlant Shop</h3>
                            <p>NurseryPlant subtitle goes here</p>
                        </div>                    
                                                    <div class="breadcrumb-content">
                                <ul class="breadcrumb">
			<li><a href="/">Home</a></li><li class="active">Product</li>
		</ul>                            </div>
                                            </div>
                                    </div>
            </div>
        </div>
    </div>
</section>

<div id="wrapper">      
	<!--<section class="section main-container ">-->
		<div class="container">    
			<div class="row">    
				<!--<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">-->
					<div class="content">
						<h1 class="page-title"></h1>
						<div class="list-wrapper clearfix">
							
							<?php if (!empty($packages)) { ?>
							<!-- Starts here -->
								<?php foreach($packages as $package): ?>
								<div class="col-md-4 col-sm-4">   
                                                                    <div class="products row" style="padding: 20px;">
									<div class="list-item">
										<!-- <div class="ribbon"><span>Sale!</span></div> -->
											<div class="entry">
												<?php $link_to_package = Url::to(['site/package-detail', 'id' => base64_encode($package->id)]); ?>
												<?php if (!empty($package->image)) { ?>
													<a href="<?= $link_to_package; ?>">
														<?= Html::img(Yii::$app->params['packageImagesUpload'] . $package->image , ['alt' => $package->name, 'title' => $package->name, 'class' => "img-responsive"]) ?>
													</a>
												<?php } else {?>
													<a href="<?= $link_to_package; ?>">
														<?= Html::img(Yii::$app->params['packagePlaceHolderImage'] , ['alt' => $package->name, 'title' => $package->name, 'class' => "img-responsive"]) ?>
													</a>
												<?php } ?>
												<div class="price-with-title">
													<h4><?= $package->name ?></h4>
													<p class="product-price">
													<!-- <del><span class="woocommerce-Price-amount amount">
													<span class="woocommerce-Price-currencySymbol">$ </span>15.00</span></del> -->
													<ins><span class="woocommerce-Price-amount amount">
													<span class="woocommerce-Price-currencySymbol">$ </span><?= $package->price ?></span></ins></p>
												</div>
												<div class="magnifier">
													<div class="price-with-title hover-des">
														<!-- <a href="#" class="button yith-wcqv-button button-quick-view" data-product_id="115"><i class="fa fa-eye"></i></a> -->
														<a rel="nofollow" href="<?= $link_to_package; ?>" data-quantity="1" data-product_id="115" data-product_sku="" class="button1 product_type_simple add_to_cart_button ajax_add_to_cart">Buy Now</a>            		
													</div>
												</div><!-- end magnifier -->
											</div>
										</div>
									</div>	
								</div>
								<?php endforeach; ?>
							<?php } ?>
							</div>
						</div>
					<!--</div>-->
				</div>
			</div>
		</div>
	<!--</section>-->
</div><!-- end wrapper -->

views/site/shop_mining.php
<?php

use borales\extensions\phoneInput\PhoneInput;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\jui\AutoComplete;
use yii\helpers\Url;
use yii\helpers\Utils;
use yii\widgets\LinkPager;

?>

<body id="bg">
	
    <div class="page-wraper">
        	
        

        
        <!-- CONTENT START -->
        <div class="page-content">
        
            <!-- INNER PAGE BANNER -->
            <div class="wt-bnr-inr overlay-wraper" style="background-image:url(images/banner/product-banner.jpg);">
            	<div class="overlay-main bg-black opacity-07"></div>
                <div class="container">
                    <div class="wt-bnr-inr-entry">
                        <h1 class="text-white">Shop</h1>
                    </div>
                </div>
            </div>
            <!-- INNER PAGE BANNER END -->
            
            <!-- BREADCRUMB ROW -->                            
            <div class="bg-gray-light p-tb20">
            	<div class="container">
                    <ul class="wt-breadcrumb breadcrumb-style-2">
                        <li><a href="javascript:void(0);"><i class="fa fa-home"></i> Home</a></li>
                        <li>Shop</li>
                    </ul>
                </div>
            </div>
            <!-- BREADCRUMB ROW END -->
            
            <!-- SECTION CONTENT START -->
            <div class="section-full p-t80 p-b50">
                <div class="container">
                    <div class="section-content">
                    	<div class="row">
                            <!-- SIDE BAR END --> 
                            <div class="col-md-12">                   
                                <!-- TITLE START -->
                                <div class="p-b10">
                                    <h2 class="text-uppercase">Our Products</h2>
                                    <div class="wt-separator-outer m-b30">
                                        <div class="wt-separator bg-primary"></div>
                                    </div>
                                </div>
                                <!-- TITLE END -->
                                
                                <div class="row">
                                    <!-- COLUMNS 1 -->
                                    <?php if (!empty($packages)) { ?>
							<!-- Starts here -->
								<?php foreach($packages as $package): ?>
                                    <div class="col-md-4 col-sm-4 col-xs-6 col-xs-100pc m-b30">
                                        <div class="wt-box wt-product-box p-a10 bg-gray">
                                            <div class="wt-thum-bx wt-img-overlay1 wt-img-effect zoom">
                                                <!--<img src="images/products/pic-1.jpg" alt="">-->
                                                
                                                <?php $link_to_package = Url::to(['site/package-detail', 'id' => base64_encode($package->id)]); ?>
                                                <?php if (!empty($package->image)) { ?>
                                                        <a href="<?= $link_to_package; ?>">
                                                                <?= Html::img(Yii::$app->params['packageImagesUpload'] . $package->image , ['alt' => $package->name, 'title' => $package->name, 'class' => "img-responsive"]) ?>
                                                        </a>
                                                <?php } else {?>
                                                        <a href="<?= $link_to_package; ?>">
                                                                <?= Html::img(Yii::$app->params['packagePlaceHolderImage'] , ['alt' => $package->name, 'title' => $package->name, 'class' => "img-responsive"]) ?>
                                                        </a>
                                                <?php } ?>
                                                
                                                <div class="overlay-bx">
                                                    <div class="overlay-icon">
<!--                                                        <a href="javascript:void(0);">
                                                            <i class="fa fa-cart-plus wt-icon-box-xs"></i>
                                                        </a>-->
<!--                                                        <a class="mfp-link" href="javascript:void(0);">
                                                            <i class="fa fa-heart wt-icon-box-xs"></i>
                                                        </a>-->
                                                  </div>
                                                </div>
                                            </div>
                                            <div class="wt-info  text-center">
                                                 <div class="p-a10 bg-white">
                                                    <h4 class="wt-title">
                                                        <!--<a href="javascript:;">One Product</a>-->
                                                        <a href="<?= $link_to_package; ?>"> <?= $package->name ?></a>
                                                    </h4>
                                                    <span class="price">
                                                        <del>
                                                             <span><span class="Price-currencySymbol">£</span>3.00</span>
         i                                               </del> 
                                                        <ins>
                                                            <span><span class="Price-currencySymbol">£</span><?= $package->price ?></span>
                                                        </ins>
                                                    </span>
                                                    <div class="rating-bx">
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                    </div>
                                                    <div class="p-t10">
                                                        <!--<button class="site-button button-sm font-weight-600" type="button">ADD TO CART</button>-->
                                                        <a class="site-button button-sm font-weight-600"  href="<?= $link_to_package; ?>">Buy Now</a> 
                                                    </div>
                                                    
                                                    
                                                 </div>
                                            </div>
                                        </div>
                                    </div>
                                                        <?php endforeach; ?>
                                                        <?php } ?>
                                </div>
                                
                                <!-- ADD BLOCK -->
                                <div class="p-tb30">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-6">
                                            <div class="wt-box pro-banner">
                                                <img src="images/add/pic1.jpg" alt="">
                                                <div class="pro-banner-disc p-a10 text-white">
                                                    <h2 class="text-uppercase m-a0 m-b10">Best time to buy</h2>
                                                    <h4 class="m-a0 m-b10">Our Product</h4>
                                                    <h3 class="text-uppercase m-a0 m-b10">UP TO</h3>
                                                    <h5 class="text-uppercase m-a0 m-b10">10% Cashback</h5>
                                                    <a href="#" class="site-button button-sm ">ADD TO CART </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6 col-sm-6">
                                            <div class="wt-box pro-banner">
                                                <img src="images/add/pic2.jpg" alt="">
                                                <div class="pro-banner-disc p-a10 text-white">
                                                    <h2 class="text-uppercase m-a0 m-b10">Best time to buy</h2>
                                                    <h4 class="m-a0 m-b10">Two Product</h4>
                                                    <h3 class="text-uppercase m-a0 m-b10">UP TO</h3>
                                                    <h5 class="text-uppercase m-a0 m-b10">40% Cashback</h5>
                                                    <a href="#" class="site-button button-sm">ADD TO CART</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- ADD BLOCK -->
                                
                            </div>                        
                            <!-- SIDE BAR START -->
                       </div> 
                   </div>
                 </div>
             </div>
             <!-- SECTION CONTENT END -->
        
        </div>
        <!-- CONTENT END -->
        


        <!-- BUTTON TOP START -->
        <!--<button class="scroltop"><span class=" iconmoon-house relative" id="btn-vibrate"></span>Top</button>-->

         
        
    </div>
    

<!-- JAVASCRIPT  FILES ========================================= --> 
<script   src="js/jquery-1.12.4.min.js"></script><!-- JQUERY.MIN JS -->
<script   src="js/bootstrap.min.js"></script><!-- BOOTSTRAP.MIN JS -->

<script   src="js/bootstrap-select.min.js"></script><!-- FORM JS -->
<script   src="js/jquery.bootstrap-touchspin.min.js"></script><!-- FORM JS -->

<script   src="js/magnific-popup.min.js"></script><!-- MAGNIFIC-POPUP JS -->

<script   src="js/waypoints.min.js"></script><!-- WAYPOINTS JS -->
<script   src="js/counterup.min.js"></script><!-- COUNTERUP JS -->
<script   src="js/waypoints-sticky.min.js"></script><!-- COUNTERUP JS -->

<script  src="js/isotope.pkgd.min.js"></script><!-- MASONRY  -->

<script   src="js/owl.carousel.min.js"></script><!-- OWL  SLIDER  -->

<script   src="js/stellar.min.js"></script><!-- PARALLAX BG IMAGE   --> 
<script   src="js/scrolla.min.js"></script><!-- ON SCROLL CONTENT ANIMTE   --> 

<script   src="js/custom.js"></script><!-- CUSTOM FUCTIONS  -->
<script   src="js/shortcode.js"></script><!-- SHORTCODE FUCTIONS  -->
<script   src="js/switcher.js"></script><!-- SWITCHER FUCTIONS  -->
<script  src="js/jquery.bgscroll.js"></script><!-- BACKGROUND SCROLL -->
<script  src="js/tickerNews.min.js"></script><!-- TICKERNEWS-->



<!-- LOADING AREA START ===== -->
<div class="loading-area">
    <div class="loading-box"></div>
    <div class="loading-pic">
        <div class="cssload-container">
            <div class="cssload-dot bg-primary"><i class="fa fa-bitcoin"></i></div>
            <div class="step" id="cssload-s1"></div>
            <div class="step" id="cssload-s2"></div>
            <div class="step" id="cssload-s3"></div>
        </div>
    </div>
</div>
<!-- LOADING AREA  END ====== -->

</body>