controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\ResetMasterPinForm;
use app\models\User;
use app\models\Order;
use \app\models\UserProfile;
use yii\web\UploadedFile;
use app\models\Balance;
use app\models\ContactForm;
use app\models\UserProfileForm;
use app\models\UserAddFundForm;
use app\models\Transaction;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\Utils;
use yii\data\Pagination;
use yii\db\Query;
use app\models\OrderSearch;
use app\models\SearchUserTreeForm;
use app\models\Package;
use yii\helpers\ArrayHelper;
use app\models\BuyTcgPointsForm;
use app\models\BroadcastMessage;
use app\models\ProfitCalculatorForm;

class UserController extends Controller {

    public $layout = "user/main";

    public function beforeAction($action) {
      if ($action->id == 'process-add-fund-request' || $action->id == 'getd-default-sponsor-id') {
        $this->enableCsrfValidation = false;
      }
      return parent::beforeAction($action);
    }



    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'profile', 'index', 'view', 'getd-default-sponsorId', 'reset-password', 'my-tree', 'contact', 'my-downline-users', 'add-fund', 'process-add-fund-request', 'add-tcg-points', 'profit-calculator'],
                'rules' => [
                    [
                        'actions' => ['logout', 'profile', 'index', 'view', 'getd-default-sponsorId', 'reset-password', 'my-tree', 'contact', 'my-downline-users', 'add-fund', 'process-add-fund-request', 'add-tcg-points', 'profit-calculator'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    //'cryptobox-callback' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $userOrderCount = Order::find()->where(['status' => 1, 'user_id' => Yii::$app->user->identity->id])->count();

        $totalUserPackageCost = Transaction::find()->where(['user_id' => Yii::$app->user->identity->id, 'status' => 1, 'transaction_mode' => 'PACKAGE PURCHASE'])->sum('paid_amount');

        
        
//        package details added
        
        $query = Package::find()
        ->where(['status' => 1])
        ->orderBy(['updated_at' => SORT_DESC]);

        // get the total number of articles (but do not fetch the article data yet)
        $count = $query->count();

        // create a pagination object with the total count
        $pagination = new Pagination(['totalCount' => $count, 'pageSize' => Yii::$app->params['pageSize']]);


        // limit the query using the pagination and retrieve the packages
        $packages = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        
        
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'userObj' => User::findOne(Yii::$app->user->identity->id),
            'userOrderCount' => $userOrderCount,
            'totalUserPackageCost' => $totalUserPackageCost,
             'packages' => $packages,
             'pages' => $pagination,
        ]);
    }

    public function actionBenefits() {
      return $this->render('benefits');
    }

    public function actionMemberarea() {
      return $this->render('memberarea');
    }

    public function actionPackage() {
      return $this->render('package');
    }

    public function actionCurrent() {
      return $this->render('current');
    }

    public function actionCalculator() {
      return $this->render('calculator');
    }

    public function actionSummary() {
      return $this->render('summary');
    }

    public function actionPayment() {
      return $this->render('payment');
    }
    
    public function actionMarketCapitalizations() {
      return $this->render('market_capitalizations');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $this->redirect(['index']);
        }
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();
        $this->redirect(['login']);
        //return $this->goHome();
    }

    /**
     * Get default Sponser Id.
     */
    public function actionGetdDefaultSponsorId() {
        if (Yii::$app->request->isAjax) {
            $sponsorId = User::find()
                    ->where(['status' => 1, 'is_admin' => 1])
                    ->orderBy(['id' => SORT_ASC])
                    ->one();
            if (!empty($sponsorId['username'])) {
                $response = Yii::$app->response;
                $response->format = \yii\web\Response::FORMAT_JSON;
                $response->data = ['sponsorId' => $sponsorId['username']];
                $response->statusCode = 200;
                return $response;
            }
        } else
            throw new \yii\web\BadRequestHttpException;
    }

    /**
     * User Profile.
     *
     */
    public function actionProfile() {

      $UserProfile = UserProfileForm::findOne([
          'user_id' => Yii::$app->user->id
      ]);

      $User = User::findOne([
        'id' => Yii::$app->user->id
      ]);

      $existing_profile_image = !empty($UserProfile->picture) ? $UserProfile->picture : NULL;
      $existing_statement_image = !empty($UserProfile->bank_statement) ? $UserProfile->bank_statement : NULL;

      if ($UserProfile->load(Yii::$app->request->post())) {

            // IF new Image uploaded, User profile pic.
            $UserProfile->picture = UploadedFile::getInstance($UserProfile, 'picture');
            if (!empty($UserProfile->picture) && $UserProfile->upload()) {
                $UserProfile->picture = $UserProfile->picture->name;
            } else {
                // Use old image/Null.
                $UserProfile->picture = $existing_profile_image;
            }

            // Bank statement.
            $UserProfile->bank_statement = UploadedFile::getInstance($UserProfile, 'bank_statement');
            if (!empty($UserProfile->bank_statement) && $UserProfile->bankStatementUpload()) {
                $UserProfile->bank_statement = $UserProfile->bank_statement->name;
            } else {
                // Use old image/Null.
                $UserProfile->bank_statement = $existing_statement_image;
            }

            // Do the operation.
            $UserProfile->date_of_birth = date('Y-m-d', strtotime($UserProfile->date_of_birth));

            if (!$UserProfile->save(false)) {
              throw new Exception("Something went wrong!. Please try again later.");
            }

            Yii::$app->session->setFlash('profileUpdate');
            return $this->refresh();
      }

      return $this->render('profile', [
          'user' => $User,
          'profile' => $UserProfile
      ]);
    }

    /**
     * User password reset.
     */

    public function actionResetPassword() {
        $User = User::findOne(Yii::$app->user->id);
        $ResetPasswordModel = new ResetPasswordForm($User, FALSE);

        if ($ResetPasswordModel->load(Yii::$app->request->post()) && $ResetPasswordModel->validate() && $ResetPasswordModel->resetPasswordForLoggedInUser()) {
            Yii::$app->session->setFlash('password-reset', 'Password Reset successful.');
            return $this->refresh();
        }
        return $this->render('reset_password', [
            'model' => $ResetPasswordModel
        ]);

    }

    /**
     * User password reset.
     */

    public function actionResetMasterPin() {
        $User = User::findOne(Yii::$app->user->id);
        $ResetMasterPinModel = new ResetMasterPinForm($User, FALSE);

        if ($ResetMasterPinModel->load(Yii::$app->request->post()) && $ResetMasterPinModel->validate() && $ResetMasterPinModel->resetMasterPinForLoggedInUser()) {
            Yii::$app->session->setFlash('master-pin-reset', 'Key Pin Reset successful.');
            return $this->refresh();
        }

        return $this->render('reset_master_pin', [
            'model' => $ResetMasterPinModel
        ]);

    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,

views/layouts/user/_binary_wallet.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\Utils;
?>


<!-- Cash Wallet: style can be found in dropdown.less -->
<li class="messages-menu binary-wallet hidden-xs hidden-sm" style="width: 80px">
    <a href="#" title="Binary Wallet">
        <i class="fa fa-street-view dashboard_icon"></i>
        <span class="label label-success"><i class="fa fa-usd"></i> <?php echo number_format(Utils::walletMoney(Yii::$app->params['wallets']['BINARY_WALLET']), 0); ?></span>
    </a>
</li>

views/layouts/user/_bonus_wallet.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\Utils;
?>


<!-- Cash Wallet: style can be found in dropdown.less -->
<li class="messages-menu bonus-wallet hidden-xs hidden-sm" style="width: 80px">
    <a href="#" title="Tradeoclub Wallet">
        <i class="fa fa-gift dashboard_icon"></i>
        <span class="label label-success"><i class="fa fa-usd"></i> <?php echo number_format(Utils::walletMoney(Yii::$app->params['wallets']['TRADEOCLUB_WALLET']), 0); ?></span>
    </a>
</li>

views/layouts/user/_cash_wallet.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\Utils;
?>


<!-- Cash Wallet: style can be found in dropdown.less -->
<li class="messages-menu cash-wallet hidden-xs hidden-sm" style="width: 80px">
    <a href="#" title="Cash Wallet">
        <i class="fa fa-money dashboard_icon"></i>
        <span class="label label-success"><i class="fa fa-usd"></i> <?php echo number_format(Utils::walletMoney(Yii::$app->params['wallets']['CASH_WALLET']), 0); ?></span>
    </a>
</li>

views/layouts/user/_promo_wallet.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\Utils;
?>


<!-- Cash Wallet: style can be found in dropdown.less -->
<li class="messages-menu tcg-wallet" style="width: 80px">
    <a href="#" title="PROMO Wallet">
        <i class="fa fa-inbox dashboard_icon"></i>
        <span class="label label-success"><i class="fa fa-hand-pointer-o"></i> <?php echo number_format(Utils::walletMoney(Yii::$app->params['secondary_wallets']['PROMO_WALLET']), 0); ?></span>
    </a>
</li>

views/layouts/user/_referral_wallet.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\Utils;
?>


<!-- Cash Wallet: style can be found in dropdown.less -->
<li class="messages-menu referral-wallet hidden-xs hidden-sm" style="width: 80px">
    <a href="#" title="Referral Wallet">
    	<i class="fa fa-users dashboard_icon"> </i>
        <span class="label label-success"><i class="fa fa-usd"></i> <?php echo number_format(Utils::walletMoney(Yii::$app->params['wallets']['REFERRAL_WALLET']), 0); ?></span>
    </a>
</li>

views/layouts/user/_server_timer.php
<?php $today = getdate(); ?>
<script>
    var d = new Date(Date.UTC(<?php echo $today['year'].",".$today['mon'].",".$today['mday'].",".$today['hours'].",".$today['minutes'].",".$today['seconds']; ?>));
    setInterval(function() {
        d.setSeconds(d.getSeconds() + 1);
        var hours = ( d.getHours() < 10 ) ? "0" + d.getHours() : d.getHours();
        var minutes = ( d.getMinutes() < 10 ) ? "0" + d.getMinutes() : d.getMinutes();
        var seconds = ( d.getSeconds() < 10 ) ? "0" + d.getSeconds() : d.getSeconds();
        $('#timer').text((hours +':' + minutes + ':' + seconds ));
    }, 1000);
</script>


<!-- Cash Wallet: style can be found in dropdown.less -->
<li class="messages-menu cash-wallet hidden-xs hidden-sm">
    <a href="#">
        <strong>Server Time :  <?php echo date('M d, Y'); ?> - </strong><label id="timer"></label>
    </a>
</li>

views/layouts/user/_user_menu.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\Utils;
?>

<!-- User Account: style can be found in dropdown.less -->

<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
<?= Html::img(Url::to(Utils::getUserPicture()), ['class' => "user-image", 'alt' => "User Image"]); ?>

        <span class="hidden-xs"><?php echo Yii::$app->user->identity->username; ?></span>
    </a>
    <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header">
                <?= Html::img(Url::to(Utils::getUserPicture()), ['class' => "img-circle", 'alt' => "User Image"]); ?>
            <p>
                <?php echo Yii::$app->user->identity->username; ?>
                <small>Member since <?php echo Yii::$app->formatter->format(Yii::$app->user->identity->created_at, 'date'); ?></small>
            </p>
        </li>

        <!-- Menu Footer-->
        <li class="user-footer">
            <div class="pull-left">
                <?=
                Html::a(
                        'Profile', ['/user/profile'], ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                )
                ?>
            </div>
            <div class="pull-right">
                <?=
                Html::a(
                        'Log out', ['/site/logout'], ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                )
                ?>
            </div>
        </li>
    </ul>
</li>

views/layouts/user/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="container">
    <div class="sub-container">
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

views/layouts/user/left.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\Utils;
?>

<style>
    .logout_button {
        color: #a1a1a1;
        font-weight: 500;
        font-size: 14px;
        background: none;
        border: none;
        padding: 15px 25px;
    }
</style>

<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <ul class="nav side-menu">
            <li class="<?php echo (Yii::$app->controller->id == 'user' && Yii::$app->controller->action->id == 'index') ? 'active' : '' ?>"><a href="<?php echo Url::to(['user/index']);?>"><i class="icon-home icons"></i> <span>Dashboard</span></a></li>
            <li class="<?php echo (Yii::$app->controller->id == 'user' && Yii::$app->controller->action->id == 'profile') ? 'active' : '' ?>"><a href="<?php echo Url::to(['user/profile']);?>"><i class="icon-people icons"></i> <span>Profile</span></a></li>
            <!--<li class="<?php echo (Yii::$app->controller->id == 'package' && Yii::$app->controller->action->id == 'purchase') ? 'active' : '' ?>"><a href="<?php echo Url::to(['package/purchase']);?>"><i class="icon-refresh icons"></i> <span>Package</span></a></li>-->
            <li class="<?php echo (Yii::$app->controller->id == 'order' && Yii::$app->controller->action->id == 'my-orders') ? 'active' : '' ?>"><a href="<?php echo Url::to(['order/my-orders']);?>"><i class="icon-docs icons"></i> <span>Orders</span></a></li>
            <li class="<?php echo (Yii::$app->controller->id == 'user' && Yii::$app->controller->action->id == 'add-fund') ? 'active' : '' ?>"><a href="<?php echo Url::to(['user/add-fund']);?>"><i class="icon-screen-desktop icons"></i> <span>Add Fund</span></a></li>
            <li class="<?php echo (Yii::$app->controller->id == 'user' && Yii::$app->controller->action->id == 'my-tree') ? 'active' : '' ?>"><a href="<?php echo Url::to(['user/my-tree']);?>"><i class="icon-organization icons"></i> <span>Tree</span></a></li>
            <li class="<?php echo (Yii::$app->controller->id == 'user' && Yii::$app->controller->action->id == 'my-downline-users') ? 'active' : '' ?>"><a href="<?php echo Url::to(['user/my-downline-users']);?>"><i class="fa fa-users"></i> <span>Downline</span></a></li>
            <li class="<?php echo (Yii::$app->controller->id == 'withdrawal' && Yii::$app->controller->action->id == 'request') ? 'active' : '' ?>"><a href="<?php echo Url::to(['withdrawal/request']);?>"><i class="icon-loop icons"></i> <span>Withdraw</span></a></li>
            <li class="<?php echo (Yii::$app->controller->id == 'transaction' && Yii::$app->controller->action->id == 'wallet-summary') ? 'active' : '' ?>"><a href="<?php echo Url::to(['transaction/wallet-summary']);?>"><i class="icon-chart icons"></i> <span>Wallet Summary</span></a></li>
            <li>
                <?= Html::beginForm(['/site/logout'], 'post', ['class' => '']); ?>
                <?=
                    Html::submitButton(
                        '<i class="icon-power icons" style="font-size: 16px;width: 16px;height: 16px;"></i> <span>Logout</span>', ['class' => 'logout_button']
                    );
                ?>
                <?= Html::endForm(); ?>
            </li>
        </ul>
    </div>
</div>

views/layouts/user/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

//dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/user/main.php
<style>
.copyrights{
    padding: 15px 0;
    z-index: 1;
    display: block;
    position: relative;
    background-color: #fed602;
    color: #1f2839;
}

ul.dropdown-menu {
    font-family: "Times New Roman", Times, serif;
}
</style>
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\DashboardAsset')) {
        backend\assets\DashboardAsset::register($this);
    } else {
        app\assets\DashboardAsset::register($this);
    }

//    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
   // echo '<pre>'; print_r($directoryAsset); exit;
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        
        <link rel="shortcut icon" href="/images/favicon/favicon.png" type="image/x-icon">
        <link rel="icon" href="/images/favicon/favicon.png" type="image/x-icon">
        
        
        <script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    </head>
    <body class="nav-md preloader-off">
    <div class="pace-cover"></div>
    <div id="st-container" class="st-container st-effect">
        <div class="container body">
            <div class="main_container">
                <?php $this->beginBody() ?>
                 <?= $this->render(
                    'header.php',
                    ['directoryAsset' => $directoryAsset]
                ) ?>
                <div class="col-md-3 left_col">
                    <div class="scroll-view">
                      <div class="navbar nav_title">
                        <h1 class="logo_wrapper">
                          <a href="/" class="site_logo">
                            <img class="logo" src="/images/logo1.jpeg" alt="cryptic logo">
                            <!--<span class="logo-text">Tradeoclub</span>-->
                          </a>
                        </h1>
                      </div>
                      <div class="clearfix"></div>
                      
                        <?= $this->render(
                            'left.php',
                            ['directoryAsset' => $directoryAsset]
                        ) ?>
                      
                    </div>
                </div>

                <?= $this->render(
                    'content.php',
                    ['content' => $content, 'directoryAsset' => $directoryAsset]
                ) ?>
                
<!--                <div class="copyrights text-center">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                Copyrights © 2018 <a href="#">Mining</a> All Rights Reserved.                            
                            </div> end col 
                        </div> end row 
                    </div> end container 
                </div>  -->
                
            </div>
        </div>
    </div>
    
    <?php $this->endBody() ?>
    
    <!-- Start of LiveChat (www.livechatinc.com) code -->
<script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 10689992;
(function() {
  var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
  lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>
<noscript>
<a href="https://www.livechatinc.com/chat-with/10689992/" rel="nofollow">Chat with us</a>,
powered by <a href="https://www.livechatinc.com/?welcome" rel="noopener nofollow" target="_blank">LiveChat</a>
</noscript>
<!-- End of LiveChat code -->
    
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>